"""
Generates the retrieval-task datasets (paper arXiv:2512.14982, Appendix A.3)
for the 6 RTL languages: pa (Punjabi, Shahmukhi), ur, ps, ar, fa, sd.

  - NameIndex   (300 items): N=50 distinct names, ask for the i-th name, i=25 fixed.
  - MiddleMatch (300 items): N=40 names drawn with replacement from K=10 names;
                             ask for the single name right between {a} and {b},
                             where the (a, X, b) triple occurs exactly once.
  - ScriptMixed  (20 items): English instruction + native-script name list.
                             NOT regenerated by default (pass --scriptmixed).

Format follows A.3: a header line ("Here's a list of names:"), then an
unnumbered list joined by the Arabic comma "، ", then the question. In the xlsx
the header + list go in "Long Data" ("<header>\n<list>") and the question in
"Query". Every item gets a freshly sampled list; RNGs are seeded per
(language, task) so output is reproducible.

Balochi is no longer generated (dropped from the study); its pools are kept only
for reference.

Run: python generate_retrieval_tasks.py [--scriptmixed]
"""

import sys
import io
import random
from pathlib import Path
from openpyxl import Workbook
from openpyxl.styles import PatternFill, Font, Alignment

DATASETS_DIR = Path(__file__).parent / "datasets"
RANDOM_SEED = 42

# Paper Appendix A.3 parameters
N_ITEMS = 300            # per task per language (paper accuracies imply n % 75 == 0)
NAMEINDEX_N = 50
NAMEINDEX_I = 25         # 1-based position asked for, fixed for every item
MIDDLEMATCH_N = 40
MIDDLEMATCH_K = 10

# ── Name lists ─────────────────────────────────────────────────────────────────

PUNJABI_50_NAMES = [
    "دلشاد بانو", "امجد فاروقی", "حمیرا اعوان", "طفیل گوندل", "عبدالحکیم",
    "ارشد چیمہ", "شاہدہ پروین", "فردوس بی بی", "اکرم گجر", "رخسانہ کوکب",
    "نسیم اختر", "شمیم اختر", "ممتاز بھٹی", "فرحت ناز", "شبیر حسین",
    "الطاف حسین", "انور شاہ", "نجمہ سعید", "غلام نبی", "اقبال ندیم",
    "شبنم گل", "اسلم پراچہ", "گلشن آرا", "نذیر لودھی", "مختار لغاری",
    "منظور الٰہی", "روبینہ بیگم", "اشرف چوہدری", "محمد یوسف", "لیاقت بلوچ",
    "نسرین مہر", "حافظ عبدالستار", "نصرت جہاں", "زیتون مائی", "رابعہ بی بی",
    "سجاد حیدر", "صبیحہ سلطانہ", "صفیہ بیگم", "مسعود کنجاہ", "سرفراز وڑائچ",
    "تسلیم فاطمہ", "ریاض کھوکھر", "ثمینہ یاسمین", "مقبول بٹ", "عاصمہ پروین",
    "حسینہ بیوی", "کلثوم بیگم", "بشیر وٹو", "خدیجہ زہرا", "پروین سلطانہ",
]

PUNJABI_10_POOL = [
    "احمد خان", "زینب اختر", "عمران شاہ", "پروین سلطانہ", "بلال حسین",
    "رابعہ بی بی", "فاطمہ بیگم", "انور شاہ", "صفیہ بیگم", "غلام نبی",
]

URDU_50_NAMES = [
    "عائشہ صدیقی", "محمد علی", "فاطمہ زہرا", "احمد رضا", "مریم انصاری",
    "عمر فاروق", "سارہ خان", "یوسف میر", "زینب حسین", "نعمان شیخ",
    "حنا قریشی", "ابراہیم سید", "صفیہ ملک", "طارق محمود", "نادیہ احمد",
    "کامران بیگ", "روبینہ طاہر", "شاہد اقبال", "نورین چوہدری", "عمران بٹ",
    "منیرہ خانم", "رفیق حیدر", "شہلا رانا", "نجم الدین", "پرویز الٰہی",
    "ثریا بیگم", "ارسلان علی", "سمیرا خالد", "ریحان انور", "بشریٰ کاظمی",
    "زاہد منیر", "آمنہ تاشفین", "قمر زمان", "صبا ناصر", "ظفر عباس",
    "ماریہ گل", "اسامہ طارق", "لبنیٰ شاہ", "وقار احمد", "حمزہ اعوان",
    "نیلوفر رضوی", "مصطفیٰ کریمی", "غزالہ بخاری", "شعیب اختر", "فریدہ پروین",
    "عدنان حق", "توقیر جاوید", "رمشا خانم", "ذوالفقار علی", "پاکیزہ بتول",
]

URDU_10_POOL = [
    "علی حسن", "مریم بیگم", "طارق عزیز", "نادیہ رضا", "کامران شاہ",
    "صبا خانم", "جاوید انور", "رشیدہ قریشی", "منصور اقبال", "شہناز بتول",
]

PASHTO_50_NAMES = [
    "زرغونه کاکړ", "ملالۍ میوند", "خوشحال خان", "احمد شاہ", "میرویس خان",
    "شاه زمان", "نازو توخۍ", "تورپیکۍ", "بټو خان", "ګل پاڼه",
    "اسفندیار ولي", "رحمان بابا", "اجمل خټک", "حمید مومند", "دریا خان",
    "سردار علي", "شیر محمد", "شریف خان", "اختر محمد", "جان محمد",
    "شاه محمود", "عبدالحی", "پاچا خان", "غني خان", "ولي خان",
    "سیف الرحمن", "نور محمد", "حیات خان", "عطا محمد", "سید جمال",
    "پیر محمد", "خان زمان", "فریدون خان", "عمر گل", "بخت جمال",
    "ظاهر شاه", "داود خان", "حبیب الله", "نجیب الله", "برهان الدین",
    "صالح محمد", "عزیز الله", "عصمت الله", "نصرت الله", "سمیع الله",
    "حکمت یار", "فضل حق", "نعمت الله", "هدایت الله", "ثناء الله",
]

PASHTO_10_POOL = [
    "احمد شاہ", "زرغونه کاکړ", "خوشحال خان", "ملالۍ میوند", "میرویس خان",
    "شاه زمان", "رحمان بابا", "غني خان", "تورپیکۍ", "حمید مومند",
]

BALOCHI_50_NAMES = [
    "میر چاکر", "میر گوہرام", "بالاچ گورگیج", "شے مرید", "ہانی بیگم",
    "بیبگر رند", "شہ داد", "میر حمل", "مہرلب", "ماہ گنج",
    "گل بی بی", "زرینہ بلوچ", "مراد بخش", "خداداد بلوچ", "عطا شاد",
    "ظفر علی", "غلام محمد", "حبیب جالب", "میر گل خان", "اکبر بارکزئی",
    "یوسف عزیز", "کریم بخش", "رحیم داد", "صالح محمد", "داد شاہ",
    "حمل ہوت", "سبزل بلوچ", "واحد بخش", "قادر بخش", "تاج محمد",
    "دوشنبہ", "شنبے خان", "سنجر خان", "سہراب خان", "نوروز خان",
    "امیر بخش", "عاصم بلوچ", "شیرین گل", "بانک کریمہ", "درناز",
    "شاہ خاتون", "بی بگر", "لعل بخش", "نود بندگ", "مراد خان",
    "خیر محمد", "اللہ بخش", "پیر داد", "روشن دین", "محمد بخش",
]

BALOCHI_10_POOL = [
    "میر چاکر", "ہانی بیگم", "بالاچ گورگیج", "شے مرید", "بیبگر رند",
    "میر حمل", "عطا شاد", "میر گل خان", "مہرلب", "گل بی بی",
]

# ── Arabic Name Pools (Curated from common Arabic names) ───────────────────────

ARABIC_50_NAMES = [
    "محمد أحمد", "عائشة فاطمة", "عبدالله محمود", "سارة علي", "خالد حسين",
    "مريم عبدالرحمن", "إبراهيم صالح", "زينب محمد", "يوسف خالد", "لمى عمر",
    "أحمد ناصر", "فاطمة عمر", "عمر خليل", "مريم سالم", "يحيى فاروق",
    "سمية علي", "عبدالعزيز راشد", "هدى عبدالنبي", "ناصر محمد", "جمال رحيم",
    "شيماء رائد", "عثمان سعيد", "بديعة أمين", "نبيل صفاء", "منى ماجد",
    "طلال كمال", "غادة صقر", "عادل نور", "سامي مسعد", "دينة فؤاد",
    "ماجد ربيع", "بشرى عازر", "فاروق جابر", "ميرنا عبدالله", "كريم أيوب",
    "لورا نزار", "أنس عبدالرازق", "داليا بهجت", "رائد قاسم", "إيمان مرسي",
    "بكر ماجد", "آية عبدالعزيز", "حسين مصطفى", "نرمين طارق", "صلاح رمضان",
    "هبة شريف", "مازن سامي", "سلمى عبدالحميد", "أمجد فؤاد", "ياروب فارس",
]

ARABIC_10_POOL = [
    "محمد أحمد", "عائشة فاطمة", "عبدالله محمود", "سارة علي", "خالد حسين",
    "عمر خليل", "يوسف خالد", "إبراهيم صالح", "زينب محمد", "فاطمة عمر",
]

# ── Persian/Farsi Name Pools (Curated from common Persian names) ─────────────────

PERSIAN_50_NAMES = [
    "علی رضا", "فاطمه حسینی", "حسین محمدی", "زینب کرمی", "محمد راد",
    "مریم بهروزی", "رضا علیزاده", "سارا نادری", "عباس غفاری", "لیلا رستمی",
    "حیدر عبداللهی", "نازنین شهابی", "امید فتاحی", "دانیال مهدوی", "ساناز حسینی",
    "بهزاد میرزایی", "نگین صدوقی", "پارسا احمدی", "ندا کشاورزی", "سیاوش منصوری",
    "پیشاوازی", "هیراد صفری", "ماندکا", "سحراب سادات", "تارا کریمی",
    "بیژن شجاعی", "ریحانه غنی", "سهیل مرادی", "آرزو موسوی", "عماد جلالی",
    "فرشته دانش", "کیان مهراد", "بهاره خوشرو", "نوید رنجبر", "مروارید دلتا",
    "ایمان نیکا", "لیموزه شاطر", "غلامحسین دهقانی", "آتنا روحانی", "سینا پناهی",
    "رناتا عسگری", "نرگس میرغفوری", "بوریس افشاری", "هدیث عزیزی", "پیمان ردا",
    "دُرَیا بیات", "شهرزاد لطفی", "سپیدار خداپرست", "فاضل نگار", "ایمین کمالی",
]

PERSIAN_10_POOL = [
    "علی رضا", "فاطمه حسینی", "حسین محمدی", "زینب کرمی", "محمد راد",
    "مریم بهروزی", "رضا علیزاده", "سارا نادری", "عباس غفاری", "لیلا رستمی",
]

# ── Sindhi Name Pools (Curated from common Sindhi names) ────────────────────────

SINDHI_50_NAMES = [
    "علی محمد", "فاطمة سماد", "حسین خان", "زینب بچر", "محمد علی",
    "مریم عبداللہ", "رضا حسینی", "سارة احمد", "عباس مولان", "لیلا راشد",
    "حیدر على", "نازنین سید", "امید خاتون", "دانیال شاه", "ساناز ميمں",
    "بهزاد مير", "نگین ابراهيم", "پارسا قاسم", "نادا موسي", "سياوش حسن",
    "پیشاوازي", "هیراد محمد", "سحراب علي", "تارا احمد", "بيژن شاه",
    "ریحانة غني", "سهیل مرادي", "آرزو موسوي", "عماد جلالي", "فرشته دانش",
    "کیان مهراد", "بهاره خوشرو", "نوید رنجبر", "مروريد لطف", "ایمان نڪا",
    "لیموزه شاطر", "غلامحسین دهقانی", "آتنا روحاني", "سينا پناغي", "رناتا عسگري",
    "نرگس ميرغفوري", "بوريس افشاري", "هديث عزيزي", "پيمان ردا", "دوريا بيات",
    "شهرزاد لطفي", "سپيدار خداپرست", "فاضل نگار", "ايمين کمالي", "موسوي شاه",
]

SINDHI_10_POOL = [
    "علی محمد", "فاطمة سماد", "حسین خان", "زینب بچر", "محمد علی",
    "مریم عبداللہ", "رضا حسینی", "سارة احمد", "عباس مولان", "لیلا راشد",
]

# ── Native prompt strings (A.3) ────────────────────────────────────────────────
# ni_header  : "Here's a list of names:"
# ni_question: "What's the 25th name?"
# mm_header  : "Here's a list (potentially with repetitions) of names:"
# mm_question: "What is the single name that appears right between {a} and {b}?"

LIST_SEP = "، "   # Arabic comma + space (all six languages use Perso-Arabic script)

PROMPTS = {
    "pa": {
        "ni_header":   "ایہہ ناواں دی اک فہرست اے:",
        "ni_question": "پچیواں ناں کیہڑا اے؟",
        "mm_header":   "ایہہ ناواں دی اک فہرست اے (ایہدے وچ ناں دہرائے وی ہو سکدے نیں):",
        "mm_question": "{a} تے {b} دے عین وچکار کیہڑا اک ناں آندا اے؟",
    },
    "ur": {
        "ni_header":   "یہ ناموں کی ایک فہرست ہے:",
        "ni_question": "پچیسواں نام کون سا ہے؟",
        "mm_header":   "یہ ناموں کی ایک فہرست ہے (اس میں نام دہرائے بھی جا سکتے ہیں):",
        "mm_question": "وہ واحد نام کون سا ہے جو {a} اور {b} کے عین درمیان آتا ہے؟",
    },
    "ps": {
        "ni_header":   "دلته د نومونو یو لېست دی:",
        "ni_question": "پنځه ویشتم نوم کوم دی؟",
        "mm_header":   "دلته د نومونو یو لېست دی (کېدای شي نومونه پکې تکرار شوي وي):",
        "mm_question": "هغه یوازینی نوم کوم دی چې سم د {a} او {b} ترمنځ راغلی دی؟",
    },
    "ar": {
        "ni_header":   "إليك قائمة بالأسماء:",
        "ni_question": "ما هو الاسم الخامس والعشرون؟",
        "mm_header":   "إليك قائمة بالأسماء (قد تتكرر فيها بعض الأسماء):",
        "mm_question": "ما هو الاسم الوحيد الذي يقع مباشرةً بين {a} و{b}؟",
    },
    "fa": {
        "ni_header":   "این فهرستی از نام‌هاست:",
        "ni_question": "نام بیست و پنجم کدام است؟",
        "mm_header":   "این فهرستی از نام‌هاست (ممکن است برخی نام‌ها تکرار شده باشند):",
        "mm_question": "تنها نامی که دقیقاً بین {a} و {b} قرار دارد کدام است؟",
    },
    "sd": {
        "ni_header":   "هتي نالن جي هڪ فهرست آهي:",
        "ni_question": "پنجويهون نالو ڪهڙو آهي؟",
        "mm_header":   "هتي نالن جي هڪ فهرست آهي (جنهن ۾ نالا ورجايل به ٿي سگهن ٿا):",
        "mm_question": "{a} ۽ {b} جي وچ ۾ ڪهڙو هڪڙو نالو آهي؟",
    },
}


def nameindex_query(lang: str) -> str:
    return PROMPTS[lang]["ni_question"]


def middlematch_query(name_a: str, name_b: str, lang: str) -> str:
    return PROMPTS[lang]["mm_question"].format(a=name_a, b=name_b)


def english_ordinal(n: int) -> str:
    suffix = {1: "st", 2: "nd", 3: "rd"}.get(n % 10 if n % 100 not in (11, 12, 13) else 0, "th")
    return f"{n}{suffix}"


# ── List formatting ─────────────────────────────────────────────────────────────

def names_to_numbered_list(names: list[str]) -> str:
    """Numbered list '1. name\n2. name\n...' (used only by ScriptMixed)."""
    return "\n".join(f"{i + 1}. {n}" for i, n in enumerate(names))


def names_to_inline(names: list[str]) -> str:
    """Unnumbered list joined with the Arabic comma, as in paper A.3."""
    return LIST_SEP.join(names)


def parse_long_data(long_data: str) -> list[str]:
    """Inverse of the Long Data format: '<header>\n<name>، <name>، ...' -> names."""
    body = long_data.split("\n", 1)[1] if "\n" in long_data else long_data
    return [n.strip() for n in body.split(LIST_SEP.strip()) if n.strip()]


# ── xlsx helpers ────────────────────────────────────────────────────────────────

YELLOW = PatternFill(start_color="FFFF00", end_color="FFFF00", fill_type="solid")
BOLD = Font(bold=True)
RTL = Alignment(horizontal="right", wrap_text=True, readingOrder=2)
LTR = Alignment(wrap_text=True)


def _header_row(ws, headers: list[str]):
    for c, h in enumerate(headers, 1):
        cell = ws.cell(row=1, column=c, value=h)
        cell.font = BOLD
        cell.alignment = LTR


def save_xlsx(items: list[dict], path: Path, sheet_title: str):
    """Save a list of dicts (keys: #, Long Data, Query, Correct Answer, Language, Task) to xlsx."""
    wb = Workbook()
    ws = wb.active
    ws.title = sheet_title
    headers = ["#", "Long Data", "Query", "Correct Answer", "Language", "Task"]
    _header_row(ws, headers)

    for item in items:
        row_num = item["#"] + 1
        for c, key in enumerate(headers, 1):
            cell = ws.cell(row=row_num, column=c, value=item[key])
            if c == 2:
                cell.fill = YELLOW
                cell.alignment = RTL
            elif c == 3:
                cell.alignment = RTL
            else:
                cell.alignment = LTR

    ws.column_dimensions["A"].width = 5
    ws.column_dimensions["B"].width = 70
    ws.column_dimensions["C"].width = 55
    ws.column_dimensions["D"].width = 25
    ws.column_dimensions["E"].width = 10
    ws.column_dimensions["F"].width = 14
    wb.save(path)
    print(f"  Saved {len(items)} items -> {path}")


# ── NameIndex generator ─────────────────────────────────────────────────────────

def gen_nameindex(names_50: list[str], lang: str, n: int = N_ITEMS) -> list[dict]:
    """n items; each a fresh random ordering of the 50 distinct names, asking for #25."""
    assert len(set(names_50)) == NAMEINDEX_N, f"{lang}: need {NAMEINDEX_N} distinct names"
    rng = random.Random(f"{RANDOM_SEED}-{lang}-NameIndex")
    header = PROMPTS[lang]["ni_header"]
    query = nameindex_query(lang)
    items = []
    for _ in range(n):
        names = rng.sample(names_50, NAMEINDEX_N)
        items.append({
            "#": len(items) + 1,
            "Long Data": f"{header}\n{names_to_inline(names)}",
            "Query": query,
            "Correct Answer": names[NAMEINDEX_I - 1],
            "Language": lang,
            "Task": "NameIndex",
        })
    return items


# ── MiddleMatch generator ───────────────────────────────────────────────────────

def middle_pair_counts(names: list[str]) -> dict:
    """{(a, b): [middles]} over every position j with names[j-1]=a, names[j+1]=b."""
    out: dict = {}
    for j in range(1, len(names) - 1):
        out.setdefault((names[j - 1], names[j + 1]), []).append(names[j])
    return out


def gen_middlematch(pool_10: list[str], lang: str, n: int = N_ITEMS) -> list[dict]:
    """
    n items; each a fresh list of N=40 names sampled uniformly with replacement
    from the K=10 pool (adjacent duplicates allowed, as in the paper's example).
    (a, b) is drawn among pairs with a != b whose triple a,X,b occurs exactly
    once in the list, so the answer X is unambiguous.
    """
    assert len(set(pool_10)) == MIDDLEMATCH_K, f"{lang}: need {MIDDLEMATCH_K} distinct names"
    rng = random.Random(f"{RANDOM_SEED}-{lang}-MiddleMatch")
    header = PROMPTS[lang]["mm_header"]
    items = []
    while len(items) < n:
        names = [rng.choice(pool_10) for _ in range(MIDDLEMATCH_N)]
        unique = sorted(
            (pair, mids[0]) for pair, mids in middle_pair_counts(names).items()
            if len(mids) == 1 and pair[0] != pair[1]
        )
        if not unique:
            continue
        (a, b), mid = rng.choice(unique)
        items.append({
            "#": len(items) + 1,
            "Long Data": f"{header}\n{names_to_inline(names)}",
            "Query": middlematch_query(a, b, lang),
            "Correct Answer": mid,
            "Language": lang,
            "Task": "MiddleMatch",
        })
    return items


# ── ScriptMixed generator ───────────────────────────────────────────────────────

def gen_scriptmixed(names_50: list[str], lang: str, n: int = 20) -> list[dict]:
    """
    Generate n ScriptMixed items.
    English instruction + native-script numbered name list; ask for position N.
    Positions: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50] × 2 shuffles = 20.
    """
    rng = random.Random(RANDOM_SEED + 2)
    positions = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
    items = []
    shuffles_per_pos = n // len(positions)

    for pos in positions:
        for _ in range(shuffles_per_pos):
            shuffled = names_50[:]
            rng.shuffle(shuffled)
            answer = shuffled[pos - 1]
            name_list_str = names_to_numbered_list(shuffled)
            ord_str = english_ordinal(pos)
            prompt = (
                f"Here's a list of names:\n{name_list_str}\n\n"
                f"What is the {ord_str} name in the list?\n"
                f"Reply with one name only."
            )
            items.append({
                "#": len(items) + 1,
                "Long Data": prompt,
                "Query": f"What is the {ord_str} name in the list?",
                "Correct Answer": answer,
                "Language": lang,
                "Task": "ScriptMixed",
            })

    return items[:n]


# ── Verification ────────────────────────────────────────────────────────────────

def verify(items: list[dict], lang: str) -> tuple[int, int]:
    """Recompute every answer from Long Data + Query. Returns (passed, total)."""
    ok = 0
    for it in items:
        names = parse_long_data(it["Long Data"])
        if it["Task"] == "NameIndex":
            good = (len(names) == NAMEINDEX_N and len(set(names)) == NAMEINDEX_N
                    and names[NAMEINDEX_I - 1] == it["Correct Answer"]
                    and it["Query"] == nameindex_query(lang))
        else:
            good = False
            if len(names) == MIDDLEMATCH_N and len(set(names)) <= MIDDLEMATCH_K:
                for (a, b), mids in middle_pair_counts(names).items():
                    if it["Query"] == middlematch_query(a, b, lang):
                        good = len(mids) == 1 and mids[0] == it["Correct Answer"]
                        break
        ok += bool(good)
    return ok, len(items)


# ── Main ────────────────────────────────────────────────────────────────────────

CONFIGS = [
    {"lang": "pa", "label": "Punjabi", "folder": "punjabi", "names_50": PUNJABI_50_NAMES, "pool_10": PUNJABI_10_POOL},
    {"lang": "ur", "label": "Urdu",    "folder": "urdu",    "names_50": URDU_50_NAMES,    "pool_10": URDU_10_POOL},
    {"lang": "ps", "label": "Pashto",  "folder": "pashto",  "names_50": PASHTO_50_NAMES,  "pool_10": PASHTO_10_POOL},
    {"lang": "ar", "label": "Arabic",  "folder": "arabic",  "names_50": ARABIC_50_NAMES,  "pool_10": ARABIC_10_POOL},
    {"lang": "fa", "label": "Persian", "folder": "persian", "names_50": PERSIAN_50_NAMES, "pool_10": PERSIAN_10_POOL},
    {"lang": "sd", "label": "Sindhi",  "folder": "sindhi",  "names_50": SINDHI_50_NAMES,  "pool_10": SINDHI_10_POOL},
]


def main():
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    write_scriptmixed = "--scriptmixed" in sys.argv[1:]
    for cfg in CONFIGS:
        lang, label = cfg["lang"], cfg["label"]
        out_dir = DATASETS_DIR / cfg["folder"]
        out_dir.mkdir(parents=True, exist_ok=True)
        print(f"\n[{label}] Generating retrieval tasks in {out_dir}...")

        ni = gen_nameindex(cfg["names_50"], lang)
        mm = gen_middlematch(cfg["pool_10"], lang)
        for items in (ni, mm):
            ok, tot = verify(items, lang)
            print(f"  verify {items[0]['Task']:<12} {ok}/{tot}")
            if ok != tot:
                raise RuntimeError(f"{lang}: verification failed")
        save_xlsx(ni, out_dir / f"NameIndex_{label}.xlsx", f"NameIndex {label}")
        save_xlsx(mm, out_dir / f"MiddleMatch_{label}.xlsx", f"MiddleMatch {label}")

        if write_scriptmixed:
            sm = gen_scriptmixed(cfg["names_50"], lang, n=20)
            save_xlsx(sm, out_dir / f"ScriptMixed_{label}.xlsx", f"ScriptMixed {label}")

    print("\nDone.")


if __name__ == "__main__":
    main()
